steps:
  multiarch-build-push:
    image: reg.hentioe.dev/library/plugin-docker-buildx
    privileged: true
    pull: true
    settings:
      repo: gramoss/telegram-bot-api
      username: gramoss
      password:
        from_secret: gramoss_password
      dockerfile: Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 2e1fb03
        - 9.1
        - latest
    when:
      branch: main
      event: push
